name: Build and Upload APK

on:
  push:
    branches:
      - master  # Cambia a la rama que desees

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.3'  # Cambia a la versión de Flutter que uses

      - name: Install dependencies
        run: flutter pub get