name: Build and Upload APK

on:
  push:
    branches:
      - master  # Cambia a la rama que desees

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload google drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: 'build/app/outputs/apk/release/app-release.apk'
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: '1WOjjbkd-OTXb0CreWV9A9cc8e2-PvTvv'